# Generated by Django 4.2.28 on 2026-02-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_employee_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='external_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
