# Generated by Django 4.2.28 on 2026-02-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_employee_external_code_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_invio',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email per invio credenziali'),
        ),
        migrations.AddField(
            model_name='employee',
            name='invito_inviato',
            field=models.BooleanField(default=False, verbose_name='Invito già inviato'),
        ),
    ]
