# Generated by Django 4.2.28 on 2026-03-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_importjob_alter_auditevent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, null=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, null=True, max_length=80),
        ),
    ]