# Generated by Django 4.2.28 on 2026-03-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_employee_full_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('pdf', models.FileField(upload_to='cud/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuds', to='portal.employee')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
