# Generated by Django 4.2.28 on 2026-03-04 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_invitetoken_cud'),
    ]

    operations = [
        migrations.CreateModel(
            name='CudView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('cud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cud')),
            ],
        ),
    ]
