# Generated by Django 4.2.28 on 2026-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_invitetoken_cudview"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="privacy_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="privacy_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
