# Generated by Django 4.2.28 on 2026-09-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_corporate_card_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalassetentry',
            name='operation_type',
            field=models.CharField(choices=[('income', 'Entrata stipendio'), ('expense', 'Uscita'), ('credit_card_expense', 'Spesa carta di credito personale'), ('credit_card_reimbursable_expense', 'Spesa carta di credito rimborsabile'), ('transfer_to_piggy_bank', 'Trasferimento conto -> salvadanaio'), ('transfer_to_account', 'Trasferimento salvadanaio -> conto'), ('reimbursable_expense', 'Spesa rimborsabile'), ('reimbursable_expense_pending', 'Spesa rimborsabile futura'), ('reimbursement_received', 'Rimborso spesa pagato'), ('advance_received', 'Anticipo ricevuto'), ('advance_returned', 'Anticipo restituito')], db_index=True, max_length=40),
        ),
    ]
